server:
  address: 0.0.0.0
  port: 8080
  forward-headers-strategy: native

spring:
  main:
    banner-mode: "off" 

voms:
  tls:
    certificate-path: /certs/voms_test_example.cert.pem
    private-key-path: /certs/voms_test_example.key.pem
    trust-anchors-dir: /etc/grid-security/certificates
    trust-anchors-refresh-interval-secs: 14400
  aa:
    host: voms.test.example
    port: ${VOMS_AA_SERVER_PORT:${server.port}}
    vo-name: ${VOMS_AA_VO_NAME}
    optional-group-label: voms.role
    use-legacy-fqan-encoding: true
