spring:
  flyway:
    out-of-order: true
  
  datasource:
    url: jdbc:mysql://${IAM_DB_HOST}:${IAM_DB_PORT}/${IAM_DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true
    username: ${IAM_DB_USERNAME}
    password: ${IAM_DB_PASSWORD}
    
    hikari:
      maximum-pool-size: 50
      minimum-idle: 8
      connection-test-query: SELECT 1