spring:
  flyway:
    out-of-order: true
  
  datasource:
    url: jdbc:mysql://${IAM_DB_HOST:dev.local.io}:${IAM_DB_PORT:3306}/${IAM_DB_NAME:iam}?useSSL=${IAM_DB_USE_SSL:false}&allowPublicKeyRetrieval=${IAM_DB_ALLOW_PUBLIC_KEY_RETRIEVAL:true}
    username: ${IAM_DB_USERNAME:iam}
    password: ${IAM_DB_PASSWORD:pwd}
    
    hikari:
      maximum-pool-size: ${IAM_DB_MAX_ACTIVE:50}
      minimum-idle: ${IAM_DB_MIN_IDLE:8}
      connection-test-query: ${IAM_DB_VALIDATION_QUERY:SELECT 1}