spring:
  
  jpa:
    open-in-view: false

  datasource:
    url: jdbc:mysql://${IAM_DB_HOST}:${IAM_DB_PORT}/${IAM_DB_NAME}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${IAM_DB_USERNAME}
    password: ${IAM_DB_PASSWORD}
    max-active: 100
    max-idle:  5
    validation-query: SELECT 1
    time-between-eviction-runs-millis: 5000
    min-evictable-idle-time-millis: 60000
  
  flyway:
    enabled: false